apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging_app
  template:
    metadata:
      labels:
        app: messaging_app
    spec:
      containers:
        - name: messaging_app
          image: ejcodes/messaging_app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: messaging_app-Service
spec:
  selector:
    app: messaging_app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
