apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app-green
  template:
    metadata:
      labels:
        app: messaging-app-green
    spec:
      containers:
        - name: messaging-app
          image: ejcodes/messaging-app:v2.0.0
          ports:
            - containerPort: 8080