# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging_app_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging_app_blue
  template:
    metadata:
      labels:
        app: messaging_app_blue
    spec:
      containers:
        - name: messaging_app
          image: ejcodes/messaging_app:latest
          ports:
            - containerPort: 8080
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: messaging_app_service
spec:
  selector:
    app: messaging_app_blue
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
