#!/usr/bin/bash

# A script to deploy a blue-green environment

# Variable holding path to deployment file
export DEPLOYMENT_FILE=/mnt/c/Users/Emmanueleg/Desktop/ALX/alx-backend-python/messaging_app/blue_deployment.yaml

# Deploy blue-green environment
kubectl apply -f "$DEPLOYMENT_FILE"

# Checks for logs in labeled pods
kubectl logs -l app=messaging-app-green
